notifications:
  email:
    on_success: never
    on_failure: never

language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - openssl aes-256-cbc -K $encrypted_16a3d0995174_key -iv $encrypted_16a3d0995174_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - npm run prettify
  - git config user.email "joshaber@gmail.com"
  - git config user.name "auto-pretty"
  - git add .
  - git commit -m "Prettier"
  - git push
